### PR TITLE
Add apps

### PR DESCRIPTION
**Pull request by guimaluf**

### CODE REVIEW

**Comment by johrstrom** [comment]
Is this something you do at your site? I think I would be OK with limiting this to `bc_desktop` app specifically, but I don't know if it's applicable generically to apps.

**Comment by guimaluf** [comment]
Yes. We do and is something mentioned on OOD docs: https://osc.github.io/ood-documentation/master/customization.html

Most of apps use `/etc/ood/config/apps` directory for hosting these configs.

**Comment by johrstrom** [comment]
Right! I'm always forgetting you configure an app in /etc/config/app but deploy it to /var/www/ood. 

OK this seeks alright on the surface, I'll need a second to look it over. Though you have so many PRs, but they all seem to be tied to one another.  If we can change that I'd be happy. The `ood-portal-generator` seems to be the only PR with logic change, and I want to get that one right especially (given now in 1.6 it returns non-zero status' so we may have to `ignore_errors`? then in 1.7 it doesn't). I want to put some work in testing that one PR out whereas the others are generally easier to pull in. 

As an aside it looks like rubygems is not entirely stable at the moment and that's why the build seems to be failing.
```bash
Installing font-awesome-sass 5.0.9
Installing sassc 2.2.1 with native extensions
Gem::RemoteFetcher::UnknownHostError: timed out
(https://rubygems.org/gems/loofah-2.4.0.gem)
An error occurred while installing loofah (2.4.0), and Bundler cannot continue.
Make sure that `gem install loofah -v '2.4.0'` succeeds before bundling.
```

**Comment by guimaluf** [comment]
> Though you have so many PRs, but they all seem to be tied to one another.

Yeah, sorry about that. The main dependency was molecule test, now it's merged is easier to split everything in its own PR

> The ood-portal-generator seems to be the only PR with logic change, and I want to get that one right especially (given now in 1.6 it returns non-zero status' so we may have to ignore_errors? then in 1.7 it doesn't)

If there is anything to improve or change let me know and I'll fix it!

**Comment by guimaluf** [comment]
This commit here is more a apps config bootstraping. I think may be a good starting for configuring apps for ondemand. I'll shortly add some sort of apps pull to the role so I can add VNC and Jupyter(which is my main goal). 

I'm willing to discuss any implementation or design for future features :)

**Comment by johrstrom** [comment]
Again, thank so much. I've rebased for you and opened #30 instead of pushing to your fork. 

Thanks again for everything and feel free to open more tickets or PRs.

**Pull request closed without merging**
