### PR TITLE
Add cluster support

### PR DESCRIPTION
**Pull request by guimaluf**

### CODE REVIEW

**Comment by johrstrom** [comment]
This is very nice.  Maybe next we could add in the ability to do multiple (not now, I can create the ticket then tackle it later).

Before I pull any of these in though I've noticed the commits aren't attributed to you.  There seems to be some misconfiguration in your git config. I can pull them in as is of course, but I think it's important you get the credit.

**Comment by johrstrom** [comment]
That said, the only bit I'm not really in love with is [this commit](https://github.com/OSC/ood-ansible/pull/24/commits/824fd13efd685746dd7c4eae9f884d5c0f759d23). I feel like a lot of those are actual *defaults* and not variable. Like those OS typed entires (like `vars/debian.yml`), those files exist because they can change during the play run based solely on OS facts, without user intervention.  They are variable and not known up front.  

But something like `nginx_config_dir: "{{ nginx_lib_dir }}/config"` is the actual default (even if it's composed) and doesn't change or isn't variable unless someone specifies it. Does that make sense?

**Comment by johrstrom** [comment]
I'm scouring the internet to figure out what `var/main.yml` could even be? I've always used `vars` as environment toggles like dev/prod or rhel/debian. I don't think I've ever seen or used them in this context.  

I'm trying to figure out if it's a matter of taste (and trivial) or an important - and I think it's important for this reason: So the user can look at one file (the defaults) and see all the things they can override or reconfigure. Then the `vars/<OS>.yml` are available just to support different operating systems. 

In my mind, defaults are just that - defaults that should work out of the box for folks, then variables are somehow computed at runtime off of os facts or similar that toggle distributions or environments.

Then things like `_connection` can be computed facts (maybe in `tasks/main.yml`).  I don't like users having to know or care about setting those things, they should just happen automagically.

**Comment by guimaluf** [comment]
> This is very nice. Maybe next we could add in the ability to do multiple (not now, I can create the ticket then tackle it later).

Yeah. I did think the same, but for now let just one :)

> Before I pull any of these in though I've noticed the commits aren't attributed to you. There seems to be some misconfiguration in your git config. I can pull them in as is of course, but I think it's important you get the credit.

thanks for pointing this out :) I added my work email to my profile and now I think is all fine ;)

> I'm scouring the internet to figure out what `var/main.yml` could even be? I've always used `vars` as environment toggles like dev/prod or rhel/debian. I don't think I've ever seen or used them in this context.
> 
> I'm trying to figure out if it's a matter of taste (and trivial) or an important - and I think it's important for this reason: So the user can look at one file (the defaults) and see all the things they can override or reconfigure. Then the `vars/<OS>.yml` are available just to support different operating systems.
> 
> In my mind, defaults are just that - defaults that should work out of the box for folks, then variables are somehow computed at runtime off of os facts or similar that toggle distributions or environments.

you're right. most of the things I moved to `vars/` shouldn't be there. I was thinking more of letting customization only on `defaults`. however it doesn't seems that is the way to do it. `vars/` has a higher precedence, so putting custom things there is definitely not a good idea.

> Then things like `_connection` can be computed facts (maybe in `tasks/main.yml`). I don't like users having to know or care about setting those things, they should just happen automagically.

Just to clarify, I've created this vars to be able to manipulate them on molecule tests. otherwise my containers would run `bin/httpd` instead of using `systemctl`. 

I'm removing the `vars/` move

**Comment by johrstrom** [comment]
Whoops! I pushed to your branch.  Sorry.  I'm ready to pull all of these in, and I can take care of the merge conflicts because I'd asked for a rebase in the other PR. 

By end of day today I think we should have all of these taken care of.

**Pull request merged**
