### PR TITLE
Add usr,sys,dev app_root path to nginx_stage

### PR DESCRIPTION
**Pull request by guimaluf**

### CODE REVIEW

**Comment by guimaluf** [comment]
Just figure out that the values assigned to defaults are not the real values for that

**Comment by johrstrom** [comment]
I seems like we'd need the `app_root:` (with the colon) because it's the top level element?

In any case, I think those are ruby computed values, so I think they should look more like this?  Though I don't know how jinja is going to deal with the `%{}` templating.
```yaml
app_root:
  dev: "{{ ood_dev_app_dir }}/%{owner}/gateway/%{name}"
  usr: "{{ ood_usr_app_dir }}/%{owner}/gateway/%{name}"
  sys: "{{ ood_usr_app_dir }}/%{name}"
```

**Comment by guimaluf** [comment]
I think I did a mass with that values.... My goal was to customise `app_root.dev` as a whole. not just the base. and `ood_dev_app_dir` is just the base name. I'll fix that :)

Since we are using yml config files for portal and nginx config would be better if we could just have a `nginx_custom_var` dict and just add them at the bottom of the templates like `{{ custom_vars | to_nice_yaml }}`

It would be nicer then cherry picking each option and mapping it here.

What do you think?

**Comment by johrstrom** [comment]
Are you suggesting for this change in `nginx_stage.yml.j2` just using `{{ nginx_app_root | to_nice_yaml }}` instead of explicitly calling out `{{ nginx_app_root.sys }}`, etc.?  I'm totally fine with that (though I'm guessing you'd have to rename nginx_app_root to just app_root).   

As long as the default definition stays the same like what you have. I think building off of other variables like `{{ ood_dev_app_dir }}` is the only thing I'd really have a strong opinion on - I don't want to get in a world were you have to define the same thing 2 or more times. Writing them out explicitly or through a jinja filter, I'm sort of ambivalent about.

**Comment by guimaluf** [comment]
> Are you suggesting for this change in `nginx_stage.yml.j2` just using `{{ nginx_app_root | to_nice_yaml }}` instead of explicitly calling out `{{ nginx_app_root.sys }}`, etc.? I'm totally fine with that (though I'm guessing you'd have to rename nginx_app_root to just app_root).

I'm suggesting something more wild and wide like `{{ nginx_stage | to_nice_yaml }}` instead of just `app_root` or other option. We could set the default and required options under `vars/main.yml` and merge user options with that to produce `nginx_stage.yml`

**Comment by johrstrom** [comment]
OK, if you want to open a ticket to talk about it more, I'm OK with that. The concern's I'd have are losing the documentation in the form of comments and it being so strangely different from the original that it would be hard to diff the 2 and easily verify we've got everything. 

Maybe comments shift `defaults/main.yml`?  Maybe it would make sense to have `defaults/nginx_stage.yml`, put them all there - with the comments.  But that's barely different from what we have now.

**Pull request merged**
